/**
 * 
 * STM32F4DISCOVERY
 * 
 * system clock output (PC9)
 * 
 */

#include <stdint.h>
#include "reg.h"


void op_sysclk(uint8_t div)
{
	//RCC
	CLEAR_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2_1_BIT);
	CLEAR_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2_0_BIT);

	if (div == 1)
		CLEAR_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_2_BIT);

	else
	{
		SET_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_2_BIT);

		if ((div - 2) >> 1)
			SET_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_1_BIT); //div == 4 or 5

		else
			CLEAR_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_1_BIT); //div == 2 or 3

		if (div & (uint8_t)1)
			SET_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_0_BIT); //div == 3 or 5

		else
			CLEAR_BIT(RCC_BASE + RCC_CFGR_OFFSET, MCO2PRE_0_BIT); //div == 2 or 4
	}

	SET_BIT(RCC_BASE + RCC_AHB1ENR_OFFSET, GPIO_EN_BIT(GPIO_PORTC));

	//GPIO
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_1_BIT(9));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_MODER_OFFSET, MODERy_0_BIT(9));

	//Output push-pull
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OTYPER_OFFSET, OTy_BIT(9));

	//OSPEEDR15 = 11 => Very high speed
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_1_BIT(9));
	SET_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_OSPEEDR_OFFSET, OSPEEDRy_0_BIT(9));

	//PUPDR15 = 00 => No pull-up, pull-down
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_1_BIT(9));
	CLEAR_BIT(GPIO_BASE(GPIO_PORTC) + GPIOx_PUPDR_OFFSET, PUPDRy_0_BIT(9));
}
